### PR TITLE
Add a license to the project

### PR DESCRIPTION
**Pull request by ggliv**
This would need to be approved by all people that have contributed to the project. @panzi @Techjar @shinyquagsire23 @WulfyStylez @CTCaer, are you guys cool with the MIT license?

### CODE REVIEW

**Comment by WulfyStylez** [comment]
fine by me!

**Comment by ggliv** [comment]
@Techjar Bump. Are you alright with the license change?

**Comment by ggliv** [comment]
Alright @shinyquagsire23, since Techjar is not responding and his only single commit was almost negligible, do you think its okay to go ahead and merge?

**Comment by shinyquagsire23** [comment]
Should be fine, yeah

**Comment by gaberilde** [comment]
Yes life is me

**Pull request merged**
